// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lecture_10.Models
{
    public partial class Students
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public decimal Gpa { get; set; }
        public string Email { get; set; }
    }
}