// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lecture_14_crawler_ex.Models;

public partial class RootDomains
{
    public int RootDomainId { get; set; }

    public string RootDomainUrlHash { get; set; }
}