// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace lecture_14_crawler_ex.Models;

public partial class Urls
{
    public string UrlHash { get; set; }

    public string Url { get; set; }

    /// <summary>
    /// 0
    /// </summary>
    public byte DepthLevel { get; set; }

    public string ParentUrlHash { get; set; }

    public bool Crawled { get; set; }

    public DateTime LastCrawlDate { get; set; }

    public byte CrawlTryCount { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string InnerText { get; set; }

    public string LinkText { get; set; }

    public DateTime DiscoveryDate { get; set; }

    public int RootDomainId { get; set; }
}